apiVersion: v1
kind: Service
metadata:
  name: blog-ui
  namespace: or-pro
spec:
  type: ClusterIP           # 配置为NodePort，外部可以访问
  ports:
    - port: 80
      targetPort: 3000     # 容器暴露的端口，与Dockerfile暴露端口保持一致
  selector:
    tier: blog-ui