quarkus:
  application:
    name: ordinaryroad-blog-quarkus
  datasource:
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/or_blog_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  http:
    access-log:
      enabled: false
      pattern: long
    cors: true
    cors.access-control-allow-credentials: true
    port: 8080
  mybatis:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  redisson:
    codec: org.redisson.codec.JsonJacksonCodec
    single-server-config:
      address: redis://${REDIS_HOST}:${REDIS_PORT}
      database: 0
  rest-client:
    gitee-oauth2:
      scope: javax.inject.Singleton
      url: https://gitee.com/api/v5
    github-oauth2:
      scope: javax.inject.Singleton
      url: https://api.github.com
    ordinaryroad:
      scope: javax.inject.Singleton
      url: https://api.ordinaryroad.tech
    ordinaryroad-auth:
      scope: javax.inject.Singleton
      url: https://auth.ordinaryroad.tech
  resteasy-json:
    default-json: false
  # Mailer
  mailer:
    from: or-mjz@qq.com
    host: smtp.qq.com
    port: 465
    ssl: true
    username: or-mjz@qq.com
    password: ${MAIL_QQ_PASSWORD}
    mock: false
    start-tls: REQUIRED
    auth-methods: DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
sa-token:
  token-name: or-blog-token
# OrdinaryRoad
ordinaryroad:
  oauth2:
    client-id: xxxxxxx
    client-secret: xxxxxx