quarkus:
  application:
    name: ordinaryroad-blog-quarkus
  # MySQL
  datasource:
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/or_blog_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: Root123.
    username: root
  http:
    access-log:
      enabled: true
      pattern: long
    cors: true
    cors.access-control-allow-credentials: true
    port: 8081
  live-reload:
    instrumentation: true
  # MyBatis https://quarkiverse.github.io/quarkiverse-docs/quarkus-mybatis/dev/index.html
  mybatis:
    # https://baomidou.com/pages/8390a4/#???-????-defaultenumtypehandler
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  native:
    additional-build-args: --report-unsupported-elements-at-runtime,--initialize-at-run-time=com.baomidou.mybatisplus.core.toolkit.support.IdeaProxyLambdaMeta
  # Redis
  redisson:
    codec: org.redisson.codec.JsonJacksonCodec
    single-server-config:
      address: redis://127.0.0.1:6379
      database: 0
  # Rest Client https://quarkus.io/guides/rest-client-reactive
  rest-client:
    gitee-oauth2:
      scope: javax.inject.Singleton
      url: https://gitee.com/api/v5
    github-oauth2:
      scope: javax.inject.Singleton
      url: https://api.github.com
    ordinaryroad:
      scope: javax.inject.Singleton
      url: https://api.ordinaryroad.tech
    ordinaryroad-auth:
      scope: javax.inject.Singleton
      url: https://auth.ordinaryroad.tech
  # Resteasy
  resteasy-json:
    default-json: false
  # Mailer
  mailer:
    from: or-mjz@qq.com
    host: smtp.qq.com
    port: 465
    ssl: true
    username: or-mjz@qq.com
    password: XXXXXX
# Sa-Token
sa-token:
  token-name: or-blog-token
