apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: or-pro
spec:
  selector:
    matchLabels:
      tier: blog
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: blog
    spec:
      containers:
        - name: blog
          image: 10.0.12.13:5000/ordinaryroad-blog
          ports:
            - containerPort: 8080
              name: blog
          env:
            - name: MYSQL_HOST
              value: "mysql.or-pro"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: "ordinaryroad"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-mysql-pass
                  key: password
            - name: REDIS_HOST
              value: "redis.or-pro"
            - name: REDIS_PORT
              value: "6379"
            - name: MAIL_QQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-mail-qq
                  key: password